### ISSUE TITLE
`TypeError: Cannot read properties of null (reading 'range')` on editing in editor

### ISSUE THREAD

**Issue by JounQin** [ota-meshi/eslint-plugin-json-schema-validator#168]
Do we need to handle invalid YAML file? Especially when integrating with an editor.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/8336744/184110826-c8d255fb-63bf-4efd-836e-a00bc1f9f50c.png">

```log
2022-08-11T10:01:48.325Z eslint:linter Parser Options: {
  ecmaVersion: 13,
  ecmaFeatures: { globalReturn: false, jsx: true },
  sourceType: 'module'
}
2022-08-11T10:01:48.326Z eslint:linter Parser Path: /Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/yaml-eslint-parser/lib/index.js
2022-08-11T10:01:48.326Z eslint:linter Settings: {}
[Error - 6:01:48 PM] ESLint stack trace:
[Error - 6:01:48 PM] TypeError: Cannot read properties of null (reading 'range')
Occurred while linting /Users/JounQin/Workspaces/GitHub/dl-iconfont/.github/workflows/ci.yml:1
Rule: "json-schema-validator/no-invalid"
    at SourceCode.getTokenBefore (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/source-code/token-store/index.js:298:18)
    at Object.key (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint-plugin-json-schema-validator/lib/utils/ast/yaml.js:81:36)
    at errorDataToLoc (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint-plugin-json-schema-validator/lib/rules/no-invalid.js:272:41)
    at /Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint-plugin-json-schema-validator/lib/rules/no-invalid.js:235:32
    at validateData (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint-plugin-json-schema-validator/lib/rules/no-invalid.js:172:29)
    at Program (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint-plugin-json-schema-validator/lib/rules/no-invalid.js:234:21)
    at ruleErrorHandler (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/linter.js:1149:32
    at Array.forEach (<anonymous>)
    at runRules (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/linter.js:1144:15)
    at Linter._verifyWithoutProcessors (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/linter.js:1393:31)
    at Linter._verifyWithoutProcessors (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint-plugin-eslint-comments/lib/utils/patch.js:181:42)
    at Linter._verifyWithConfigArray (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/linter.js:1762:21)
    at Linter.verify (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/linter.js:1475:65)
    at Linter.ESLinter.verify (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint-plugin-mdx/lib/processors/options.js:33:19)
    at Linter.verifyAndFix (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/linter/linter.js:2021:29)
    at verifyText (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/cli-engine/cli-engine.js:245:48)
    at CLIEngine.executeOnText (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/cli-engine/cli-engine.js:917:26)
    at ESLint.lintText (/Users/JounQin/Workspaces/GitHub/dl-iconfont/node_modules/eslint/lib/eslint/eslint.js:592:23)
    at /Users/JounQin/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:23205
    at E (/Users/JounQin/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:18310)
    at Object.e.validate (/Users/JounQin/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:23164)
    at /Users/JounQin/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:210200
```

**Comment by ota-meshi** [comment]
Can you provide a YAML that can reproduce the issue?

**Comment by JounQin** [comment]
Sure

https://github.com/un-ts/dl-iconfont/blob/main/.github/workflows/size-limit.yml

```yaml
name: Size Limit

on:
  pull_request_target:
    branches:
      - main

jobs:
  size-limit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: install
          script: yarn size-limit --json

      -

```
